//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVentaRopaEntities : DbContext
    {
        public DBVentaRopaEntities()
            : base("name=DBVentaRopaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAdministrador> tblAdministradors { get; set; }
        public virtual DbSet<tblCajero> tblCajeroes { get; set; }
        public virtual DbSet<tblCiudad> tblCiudads { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblDepartamento> tblDepartamentoes { get; set; }
        public virtual DbSet<tblDevolucione> tblDevoluciones { get; set; }
        public virtual DbSet<tblMarca> tblMarcas { get; set; }
        public virtual DbSet<tblMetodoPago> tblMetodoPagoes { get; set; }
        public virtual DbSet<tblPrenda> tblPrendas { get; set; }
        public virtual DbSet<tblProveedor> tblProveedors { get; set; }
        public virtual DbSet<tblSede> tblSedes { get; set; }
        public virtual DbSet<tblTalla> tblTallas { get; set; }
        public virtual DbSet<tblTipoDocuman> tblTipoDocumen { get; set; }
        public virtual DbSet<tblVendedor> tblVendedors { get; set; }
        public virtual DbSet<tblVenta> tblVentas { get; set; }
    }
}
