//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdministrador
    {
        public string idAdministrador { get; set; }
        public string NombreAdministrador { get; set; }
        public System.DateTime fechaNacimientoAdministrador { get; set; }
        public long TelefonoAdministrador { get; set; }
        public string EmailAdministrador { get; set; }
        public int TipoDocumentoAdministrador { get; set; }
    
        public virtual tblTipoDocuman tblTipoDocuman { get; set; }
    }
}
