//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblDevolucione : Base
    {
        public string idDevolucion { get; set; }
        public string idVentaDevolucion { get; set; }
        public string motivoDevolucion { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
        
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblVenta tblVenta { get; set; }
    }
}
