//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblPrenda : Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPrenda()
        {
            this.tblProveedors = new HashSet<tblProveedor>();
            this.tblVentas = new HashSet<tblVenta>();
        }
    
        public int idPrenda { get; set; }
        public int idMarcaPrenda { get; set; }
        public int idTallaPrenda { get; set; }
        public double precio { get; set; }
        public int Cantidad { get; set; }
        public string NombrePrenda { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblMarca tblMarca { get; set; }
        
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblTalla tblTalla { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblProveedor> tblProveedors { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblVenta> tblVentas { get; set; }
    }
}
