//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedor : Base
    {
        public string idProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public long TelefonoProveedor { get; set; }
        public string EmailProveedor { get; set; }
        public string DireccionProveedor { get; set; }
        public int idPrendaProveedor { get; set; }
    
        public virtual tblPrenda tblPrenda { get; set; }
    }
}
