//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblVenta : Base
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVenta()
        {
            this.tblDevoluciones = new HashSet<tblDevolucione>();
        }
    
        public string idVenta { get; set; }
        public int idPrendaVenta { get; set; }
        public string idClienteVenta { get; set; }
        public string idVendedorVenta { get; set; }
        public int idMetodoPagoVenta { get; set; }
        public int idSedeVenta { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public int cantidad { get; set; }
        public double totalVenta { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblDevolucione> tblDevoluciones { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblMetodoPago tblMetodoPago { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblPrenda tblPrenda { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblSede tblSede { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblVendedor tblVendedor { get; set; }
    }
}
